baseURL = "https://juliambrosman.github.io/scgc-bioinfo-hugo/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Bioinformatics of Microbial Single Cell Genomes"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

publishDir = "docs"

[Params]

    # Souce Code repository section
    description = "2020 Course Website"
    github_repository = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = ""

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    title = "Hugo Techdoc Theme"
    images = ["images/BL_Logo_White.png"]
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = "#003366"

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
        "images"
    ]

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Twitter"
    url = ""
    weight = 2

[[menu.main]]
    name = "SCGC"
    url = "https://scgc.bigelow.org/"
    weight = 3

[[main.menu]]
    name = "Bigelow"
    url = "https://bigelow.org"
    weight = 4
